const fs = require('fs');
const path = require('path');
const { makeLogger } = require('../utils/logger');

const logger = makeLogger('charts');
const CHARTS_DIR = path.join(__dirname, '..', '..', 'data', 'charts');

const cache = new Map(); // icao -> formatted text block, or null if not found

/**
 * Returns a formatted text block of real chart data (runways, taxiways,
 * frequencies) for the given ICAO code, for injection into the LLM's
 * context so it references actual airport layout instead of inventing
 * taxiway names. Returns null if no chart data exists for that airport -
 * callers should just skip the context block in that case.
 *
 * Chart data comes from data/charts/<ICAO>.json, generated by
 * scripts/extract-charts.js from the community PTFS Charts repo
 * (https://github.com/Treelon/ptfs-charts, CC-BY-SA-4.0) - see that
 * script's header comment for how the extraction works and its limits.
 */
function getChartContext(icao) {
  if (!icao) return null;
  const key = icao.toUpperCase();

  if (cache.has(key)) return cache.get(key);

  let text = null;
  try {
    const filePath = path.join(CHARTS_DIR, `${key}.json`);
    const chart = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    text = formatChart(chart);
  } catch (err) {
    if (err.code !== 'ENOENT') {
      logger.warn(`Failed to load chart data for ${key}: ${err.message}`);
    }
  }

  cache.set(key, text);
  return text;
}

function formatChart(chart) {
  const lines = [
    `Real chart data for ${chart.icao}${chart.name ? ` (${chart.name})` : ''} - use these actual taxiway/runway/frequency names instead of inventing your own:`,
  ];

  if (chart.runways.length > 0) {
    const runwayText = chart.runways
      .map((r) => `${r.designator} (heading ${r.heading}${r.length ? `, ${r.length.feet}/${r.length.meters}` : ''})`)
      .join(', ');
    lines.push(`Runways: ${runwayText}`);
  }

  if (chart.frequencies.length > 0) {
    const freqText = chart.frequencies.map((f) => `${f.facility} ${f.frequency}`).join(', ');
    lines.push(`Frequencies: ${freqText}`);
  }

  if (chart.otherLabels.length > 0) {
    lines.push(`Other chart labels (taxiways, aprons, gates, buildings): ${chart.otherLabels.join(', ')}`);
  }

  return lines.join('\n');
}

module.exports = { getChartContext };
